version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://si5_sacc:dev_password@database/td_1
    depends_on:
      - database
      - redis
    volumes:
      - .:/code
    command: flask run --host=0.0.0.0

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
