apiVersion: apps/v1
kind: Deployment
metadata:
  name: polymetrie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polymetrie-app
  template:
    metadata:
      labels:
        app: polymetrie-app
    spec:
      containers:
      - name: polymetrie-container
        image: igormel/polymetrie:1.1
        ports:
          - containerPort: 8080