apiVersion: v1
kind: Service
metadata:
  name: polymetrie-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: polymetrie-app