apiVersion: apps/v2
kind: Deployment
metadata:
  name: polymetrie-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polymetrie-app
  template:
    metadata:
      labels:
        app: polymetrie-app
    spec:
      containers:
      - name: polymetrie-container
        image: igormel/polymetrie:6
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-postgresql
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-redis
              key: redis-password
        ports:
          - containerPort: 8080