apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polymetrie-d-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:pns-si5-cloud/orchestration-at-scale-23-24-polymetrie-d.git
    targetRevision: HEAD
    path: kube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true # delete resources that are not in git
      selfHeal: true # reconcile differences between git and cluster

