name: Send to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment:
      name: Main
    outputs:
      new_version: ${{ steps.auto_increment.outputs.new_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Download previous checksum
        uses: actions/download-artifact@v2
        with:
          name: main_py_checksum
          path: ${{ github.workspace }}

      - name: Calculate Checksum
        id: checksum
        run: |
          sha256sum main.py | awk '{print $1}' > checksum.txt
          echo "main_py_checksum=$(cat checksum.txt)" >> $GITHUB_ENV


      - name: Compare Checksum
        id: compare_checksum
        run: |
          if [ -f ${{ github.workspace }}/main_py_checksum ]; then
            if diff checksum.txt ${{ github.workspace }}/main_py_checksum; then
              echo "::set-output name=changed::false"
            else
              echo "::set-output name=changed::true"
            fi
          else
            echo "::set-output name=changed::true"
          fi

      - name: Stop if no changes detected
        if: steps.compare_checksum.outputs.changed == 'false'
        run: |
          echo "No changes detected in main.py"
          exit 0

      - name: Store Checksum
        uses: actions/upload-artifact@v2
        with:
          name: main_py_checksum
          path: checksum.txt

      - name: Git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull

      - name: Auto-increment version and commit
        id: auto_increment
        run: |
          VERSION=$(grep 'image:' kube/polymetrie_deployment.yml | awk -F ':' '{print $3}' | xargs)
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          sed -i 's/\(image: igormel\/polymetrie:\)[0-9]*/\1'"$NEW_VERSION"'/' kube/polymetrie_deployment.yml
          echo "::set-output name=new_version::$NEW_VERSION"
          cat kube/polymetrie_deployment.yml
          git add kube/polymetrie_deployment.yml
          git commit -m "Increment image version to $NEW_VERSION"

      - name: Commit and push
        run: |
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: igormel/polymetrie:${{ steps.auto_increment.outputs.new_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
